// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1754308773);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1754299407);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1754299390);
user_pref("app.update.lastUpdateTime.region-update-timer", 1754309018);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1754308629);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1754299527);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1754308652);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1754299437);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1754308896);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1754299376);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f8602c23-fa62-40d6-93f1-8acad74a7a7e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1754299383);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1754315874413");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1754317696413");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1754299392135");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1754320992135");
user_pref("browser.search.region", "ES");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210318103112");
user_pref("browser.slowStartup.averageTime", 4602);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20210318103112");
user_pref("browser.startup.homepage_override.mstone", "87.0");
user_pref("browser.startup.lastColdStartupCheck", 1754308622);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1754299386337");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "87.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "561193d18cf0432ba960d9d896fb8543");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1754308773);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210318103112");
user_pref("extensions.lastAppVersion", "87.0");
user_pref("extensions.lastPlatformVersion", "87.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{417c9369-d4d5-4a95-9b79-d00a83b21f3d}\",\"addons\":{\"proxy-failover@mozilla.com\":{\"version\":\"1.0.1\"}}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e346eecd-4a62-46f5-92f8-40b870d397ef\",\"formautofill@mozilla.org\":\"4df33378-d197-485f-af17-7d859ddc2cba\",\"screenshots@mozilla.org\":\"7994c466-78db-4ab4-9ebb-3cf17d2563f5\",\"webcompat-reporter@mozilla.org\":\"f6939455-b5dd-413c-b8b4-8cc30e5b3bd9\",\"webcompat@mozilla.org\":\"d1bc1118-7b76-493f-b314-ad8dad3dddad\",\"default-theme@mozilla.org\":\"5204c2ae-00df-4e94-81b2-3eaf1d2c20a9\",\"google@search.mozilla.org\":\"284b9aca-4529-4cb9-b4c1-3d2b7fb67016\",\"amazondotcom@search.mozilla.org\":\"e114f348-0708-4a50-a3b8-729fb84f193c\",\"wikipedia@search.mozilla.org\":\"2baa21eb-1392-4d97-bba5-3edeeccf3e16\",\"bing@search.mozilla.org\":\"94aa8973-dfb9-48a4-abca-4f6114053b9d\",\"ddg@search.mozilla.org\":\"83a81052-f503-428d-bc45-8d56f52c47ed\",\"proxy-failover@mozilla.com\":\"3ffcfd57-180e-4277-a95c-a4ed4d7bd5e5\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1754299389);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1754308836);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1754299447);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20210318103112");
user_pref("media.gmp-manager.lastCheck", 1754299445);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1754308837);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1754308837053");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "e86e3d49-2594-4bd9-a888-c6e1fc41b386");
user_pref("security.sandbox.plugin.tempDirSuffix", "95ed8834-0ef3-4942-8d15-0e95b79f5679");
user_pref("services.blocklist.plugins.checked", 1754313131);
user_pref("services.settings.clock_skew_seconds", 2705);
user_pref("services.settings.last_update_seconds", 1754313131);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1754313131);
user_pref("services.settings.main.hijack-blocklists.last_check", 1754313131);
user_pref("services.settings.main.message-groups.last_check", 1754308626);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1754308626);
user_pref("services.settings.main.sites-classification.last_check", 1754313131);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1754308837);
user_pref("toolkit.startup.last_success", 1754308620);
user_pref("toolkit.telemetry.cachedClientID", "3fbd81ad-dc24-42f6-9f56-8d2b5d80bf4b");
user_pref("toolkit.telemetry.previousBuildID", "20210318103112");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
