// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1752590140);
user_pref("app.update.lastUpdateTime.region-update-timer", 1752590140);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1752590140);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1752590170);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1752590140);
user_pref("browser.region.update.updated", 1752590113);
user_pref("browser.search.region", "ES");
user_pref("calendar.caldav.googleResync", 1752590112);
user_pref("calendar.list.sortOrder", "5c872c22-87fc-412d-9a19-e37b8dec84c6");
user_pref("calendar.registry.5c872c22-87fc-412d-9a19-e37b8dec84c6.calendar-main-default", true);
user_pref("calendar.registry.5c872c22-87fc-412d-9a19-e37b8dec84c6.calendar-main-in-composite", true);
user_pref("calendar.registry.5c872c22-87fc-412d-9a19-e37b8dec84c6.disabled", true);
user_pref("calendar.registry.5c872c22-87fc-412d-9a19-e37b8dec84c6.name", "Home");
user_pref("calendar.registry.5c872c22-87fc-412d-9a19-e37b8dec84c6.type", "storage");
user_pref("calendar.registry.5c872c22-87fc-412d-9a19-e37b8dec84c6.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "UTC");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1752590121814");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1752590140);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241211204238");
user_pref("extensions.lastAppVersion", "115.18.0");
user_pref("extensions.lastPlatformVersion", "115.18.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"dc5e606c-b333-4dfa-8008-d2bb0c88ab27\",\"google@search.mozilla.org\":\"14cd0c45-47dd-4453-82dc-9a6ae351f1d0\",\"ddg@search.mozilla.org\":\"bfee4b58-7df2-4061-b274-a6463f3418a0\",\"amazondotcom@search.mozilla.org\":\"44a55dac-2327-448e-96f7-dbdb3b5052af\",\"wikipedia@search.mozilla.org\":\"2601974f-dd9e-4c35-9ac1-bcd1d2bf9add\",\"bing@search.mozilla.org\":\"3776fc35-0dc6-4e20-9bee-734065238016\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1752590289);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "52e1d5a2-c9bb-43d0-af12-65b13ca14b4");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.18.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1752590289);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -20145);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1752610285);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1752610285);
user_pref("services.settings.thunderbird.search-config.last_check", 1752610285);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1752610285);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1752590289);
user_pref("toolkit.startup.last_success", 1752590108);
user_pref("toolkit.telemetry.cachedClientID", "c8104daa-3835-4eb6-b7cc-0731b965be7f");
user_pref("toolkit.telemetry.previousBuildID", "20241211204238");
