services:

  apache_server:
    build: ./apache_server
    container_name: apache_server
    ports:
      - "2222:22"
      - "8080:80"
      - "8443:443"
    networks:
      red_privada:
        ipv4_address: 172.20.0.11
    volumes:
      - ./apache_server/web:/var/www/html
      - ./apache_server/msmtprc:/etc/msmtprc
    cap_add:
      - NET_ADMIN
    depends_on:
      - mail_server

  mysql_server:
    build: ./mysql_server
    container_name: mysql_server
    ports:
      - "3306:3306"
      - "2223:22"
    networks:
      red_privada:
        ipv4_address: 172.20.0.12
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    cap_add:
      - NET_ADMIN

  dns_server:
    build: ./dns_server
    container_name: dns_server
    ports:
      - "2224:22"
    networks:
      red_privada:
        ipv4_address: 172.20.0.10
    cap_add:
      - NET_ADMIN

  mail_server:
    build: ./mail_server
    container_name: mail_server
    hostname: mail_server
    domainname: masterciberseguridad.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
    networks:
      red_privada:
        ipv4_address: 172.20.0.13
    volumes:
      - ./maildata/mail:/var/mail
      - ./maildata/state:/var/mail-state
      - ./maildata/log:/var/log/mail
      - ./maildata/config:/tmp/docker-mailserver
      - ./sendmail.php:/var/www/html/sendmail.php
      - ./msmtprc:/etc/msmtprc
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - PERMIT_DOCKER=network
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

  proxy_server:
    build: ./proxy_server
    container_name: proxy_server
    ports:
      - "3128:3128"
      - "2226:22"
    networks:
      red_privada:
        ipv4_address: 172.20.0.14
    cap_add:
      - NET_ADMIN

  grafana_server:
    build: ./grafana_server
    container_name: grafana_server
    ports:
      - "3000:3000"
    networks:
      red_privada:
        ipv4_address: 172.20.0.15
    cap_add:
      - NET_ADMIN

  user:
    build: ./user
    container_name: user
    ports:
      - "6080:80"
    networks:
      red_privada:
        ipv4_address: 172.20.0.5
    dns:
      - 172.20.0.10
    volumes:
      - ./user/home:/root
    depends_on:
      - dns_server
    privileged: true
    cap_add:
      - NET_ADMIN

  router:
    build: ./router
    container_name: router
    privileged: true
    ports:
      - "2225:22"
    networks:
      red_privada:
        ipv4_address: 172.20.0.254
      red_publica:
        ipv4_address: 203.0.113.20
    dns:
      - 172.20.0.10
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  attacker:
    build: ./attacker
    container_name: attacker
    stdin_open: true
    tty: true
    ports:
      - "2227:22"
      - "6081:80"
    networks:
      red_publica:
        ipv4_address: 203.0.113.30
      red_ataque:
        ipv4_address: 10.20.30.5
    dns:
      - 203.0.113.20
    depends_on:
      - router
    cap_add:
      - NET_ADMIN
    volumes:
      - ./attacker/home:/root

networks:
  red_privada:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  red_ataque:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.30.0/24
  red_publica:
    driver: bridge
    ipam:
      config:
        - subnet: 203.0.113.0/24
